services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - ../../metrics_server/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - task-net
      
volumes:
  db-data:

networks:
  task-net: