services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - ../../metrics_server/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - task-net
  server:
    build: 
      context: ..
      dockerfile: ./build/server/Dockerfile
    container_name: server
    depends_on: 
      - postgres
    ports: 
      - "8083:8083"
      - "50051:50051"
    networks:
      - task-net
  migrator:
    build: 
      context: ..
      dockerfile: ./build/migrator/Dockerfile
    container_name: migrator
    depends_on: 
      - postgres
    ports: 
      - "8082:8082"
    networks:
      - task-net
volumes:
  db-data:

networks:
  task-net: